name: "parse-tag"
description: "Parse a tag"
inputs:
  tag:
    description: "The tag."
    required: false
outputs:
  project-name:
    description: "The name of the project."
  project-version:
    description: "The version of the project."
runs:
  using: "node16"
  main: "dist/index.js"
