name: "Units Test"
on:
  pull_request:
  push:
#    branches:
#      - main
#      - "releases/*"

jobs:
  # Run unit tests.
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # Verify the action in an actual workflow.
  use:
    runs-on: ubuntu-latest
    outputs:
      as-tag-name: "${{steps.as-tag.outputs.project-name}}"
      as-ref-name: "${{steps.as-ref.outputs.project-name}}"
      as-tag-version: "${{steps.as-tag.outputs.project-version}}"
      as-ref-version: "${{steps.as-ref.outputs.project-version}}"
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: as-tag
        with:
          tag: tag-name/tag-version
      - uses: ./
        id: as-ref
        with:
          tag: refs/tags/ref-name/ref-version
      - name: Verify in the same workflow
        run: |
          [ "${{steps.as-tag.outputs.project-name}}" = "tag-name" ]
          [ "${{steps.as-ref.outputs.project-name}}" = "ref-name" ]
          [ "${{steps.as-tag.outputs.project-version}}" = "tag-version" ]
          [ "${{steps.as-ref.outputs.project-version}}" = "ref-version" ]
  verify:
    runs-on: ubuntu-latest
    needs: use
    steps:
      - run: |
          [ "${{needs.use.outputs.as-tag-name}}" = "tag-name" ]
          [ "${{needs.use.outputs.as-ref-name}}" = "ref-name" ]
          [ "${{needs.use.outputs.as-tag-version}}" = "tag-version" ]
          [ "${{needs.use.outputs.as-ref-version}}" = "ref-version" ]
