name: "Test"
on:
  pull_request:
  push:

jobs:
  # Run unit tests.
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # Verify the action in an actual workflow.
  use:
    runs-on: ubuntu-latest
    outputs:
      as-tag-name: "${{steps.as-tag.outputs.project-name}}"
      as-ref-name: "${{steps.as-ref.outputs.project-name}}"
      as-tag-version: "${{steps.as-tag.outputs.project-version}}"
      as-ref-version: "${{steps.as-ref.outputs.project-version}}"
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Write changelog file
        run: |
          cat <<EOF > changelog.md
          # Changelog
          
          Bla blah
          
          ## [1.0] - first version
          
          All beginnings are hard. Forgive us.
          
          ## [2.0] - best version
          
          Much improvements. Very feature. Upgraded yesterday, never regrets.
          
          Much wow.
          
          ## [2.1] - approved version
          
          This version sucks. Don't upgrade. Stay on 2.0 without support forever.
          EOF
      - name: Extract changelog section
        uses: ./
        id: changelog
        with:
          file: changelog.md
          version: "2.0"
      - name: Access output, verifying that extraction section is correct and trimmed
        run: |
          section="$(
          cat <<EOF
          Much improvements. Very feature. Upgraded yesterday, never regrets.

          Much wow.
          EOF
          )"
          [ "${{steps.changelog.outputs.section}}" = "${section}" ]
